language: node_js
node_js:
  - "6.3"
addons:
  code_climate:
    repo_token: c1417b78f23a4495e9b23dd39f5d1153441f949c1b4ac238f34c475729b89b8f
after_script:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < lcov.info
